#!/usr/bin/env python3
"""Traceability scan (REQUIREMENTS-MANAGEMENT.md §4.3).

    python3 scripts/trace.py             regenerate requirements/TRACE.md
    python3 scripts/trace.py --coverage  report only: coverage gaps and the
                                         status transitions the evidence supports
    python3 scripts/trace.py --check     exit 1 if requirements/TRACE.md is stale

Standard library only. Requirement and step files are read, never edited:
applying a status transition stays with whoever runs §4.3 step 5.
"""
import argparse
import datetime
import difflib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Scan configuration: the single source for REQUIREMENTS-MANAGEMENT.md §4.2.
# A trailing "/" marks a directory; anything else is one file.
CODE_ROOT = "src/"
TEST_ROOT = "tests/"
ALSO_IMPLEMENTS = ["dev", "dev.ps1", "scripts/", ".github/workflows/", ".githooks/"]
ALSO_VERIFIES = ["scripts/"]

TRACE = "requirements/TRACE.md"
ARCHITECTURE = "ARCHITECTURE.md"
STATUSES = ("draft", "approved", "implemented", "verified", "needs-reverify",
            "superseded", "rejected")
FOLDERS = ("todo", "doing", "done")

REQ_ID = r"REQ-[A-Z0-9]+-\d+"
TAG_RE = re.compile(r"\b(implements|verifies|supports):\s*(%s(?:\s*,\s*%s)*)" % (REQ_ID, REQ_ID))
BODY_START = "## Scan inputs"
HEADER = ("<!-- GENERATED by scripts/trace.py (REQUIREMENTS-MANAGEMENT.md §4.3) — "
          "do not hand-edit. Regenerate: ./dev trace -->")


class TraceError(Exception):
    pass


# --- frontmatter: the YAML subset the two TEMPLATE.md files use ---------------

def _strip_comment(line):
    quote = None
    for i, ch in enumerate(line):
        if quote:
            if ch == quote:
                quote = None
        elif ch in "\"'" and (i == 0 or line[i - 1] in " \t[,{:"):
            quote = ch
        elif ch == "#" and (i == 0 or line[i - 1].isspace()):
            return line[:i]
    return line


def _split(text):
    """Split on commas that are outside quotes and brackets."""
    parts, cur, depth, quote = [], "", 0, None
    for ch in text:
        if quote:
            quote = None if ch == quote else quote
        elif ch in "\"'":
            quote = ch
        elif ch in "[{":
            depth += 1
        elif ch in "]}":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
            continue
        cur += ch
    if cur.strip():
        parts.append(cur)
    return parts


def _scalar(text):
    text = text.strip()
    if text in ("", "null", "~"):
        return None
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
        return text[1:-1]
    if text.startswith("[") and text.endswith("]"):
        return [_scalar(p) for p in _split(text[1:-1])]
    if text.startswith("{") and text.endswith("}"):
        pairs = (p.partition(":") for p in _split(text[1:-1]))
        return {k.strip(): _scalar(v) for k, _, v in pairs}
    return text


def _is_item(content):
    return content == "-" or content.startswith("- ")


def _block(items, i, indent):
    """Parse items[i:] at this indent into a list or dict; return (value, next i)."""
    if _is_item(items[i][1]):
        out = []
        while i < len(items) and items[i][0] == indent and _is_item(items[i][1]):
            rest = items[i][1][1:].strip()
            if not rest and i + 1 < len(items) and items[i + 1][0] > indent:
                value, i = _block(items, i + 1, items[i + 1][0])
            elif re.match(r"[A-Za-z_][\w-]*:(\s|$)", rest):
                items[i] = (indent + 2, rest)         # a map written inside the list
                value, i = _block(items, i, indent + 2)
            else:
                value, i = _scalar(rest), i + 1
            out.append(value)
        return out, i
    out = {}
    while i < len(items) and items[i][0] == indent and not _is_item(items[i][1]):
        key, sep, rest = items[i][1].partition(":")
        if not sep:
            raise TraceError("expected 'key: value', got '%s'" % items[i][1])
        key, rest = key.strip(), rest.strip()
        i += 1
        if rest:
            out[key] = _scalar(rest)
            while i < len(items) and items[i][0] > indent:   # continuation lines
                i += 1
        elif i < len(items) and (items[i][0] > indent or
                                 (items[i][0] == indent and _is_item(items[i][1]))):
            out[key], i = _block(items, i, items[i][0])
        else:
            out[key] = None
    return out, i


def frontmatter(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    try:
        if lines[0].strip() != "---":
            raise ValueError
        end = next(n for n, line in enumerate(lines[1:], 1) if line.strip() == "---")
    except (IndexError, ValueError, StopIteration):
        raise TraceError("%s: no '---' frontmatter block" % rel(path))
    items = []
    for line in lines[1:end]:
        line = _strip_comment(line).rstrip()
        if line.strip():
            items.append((len(line) - len(line.lstrip()), line.strip()))
    if not items:
        return {}
    try:
        data, used = _block(items, 0, items[0][0])
    except TraceError as err:
        raise TraceError("%s: %s" % (rel(path), err))
    if used != len(items) or not isinstance(data, dict):
        raise TraceError("%s: unsupported frontmatter near '%s'"
                         % (rel(path), items[min(used, len(items) - 1)][1]))
    return data


# --- scan -------------------------------------------------------------------

def rel(path):
    return path.relative_to(ROOT).as_posix()


def as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def files_under(roots):
    """Tracked and untracked-but-not-ignored files under the roots, sorted."""
    names = [r.rstrip("/") for r in roots]
    try:
        out = subprocess.run(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--"] + names,
            cwd=ROOT, check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout
        found = [p for p in out.decode("utf-8", "replace").split("\0") if p]
    except (OSError, subprocess.CalledProcessError):       # not a git checkout
        found = []
        for name in names:
            path = ROOT / name
            found += [rel(p) for p in path.rglob("*")] if path.is_dir() else [name]
    return sorted(p for p in set(found) if (ROOT / p).is_file())


def scan_tags(roots, kinds):
    """{kind: {req id: [(file, line), ...]}} for the tag kinds scanned in these roots."""
    tags = {kind: {} for kind in kinds}
    for name in files_under(roots):
        try:
            text = (ROOT / name).read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for number, line in enumerate(text.splitlines(), 1):
            for match in TAG_RE.finditer(line):
                if match.group(1) in kinds:
                    for req in re.findall(REQ_ID, match.group(2)):
                        tags[match.group(1)].setdefault(req, []).append((name, number))
    return tags


def anchors():
    """GitHub heading slugs of ARCHITECTURE.md."""
    path = ROOT / ARCHITECTURE
    if not path.is_file():
        return set()
    slugs, seen, fenced = set(), {}, False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.lstrip().startswith("```"):
            fenced = not fenced
        match = None if fenced else re.match(r"#{1,6}\s+(.*?)\s*#*\s*$", line)
        if match:
            slug = re.sub(r"[^\w\- ]", "", match.group(1).lower()).replace(" ", "-")
            count = seen.get(slug, 0)
            seen[slug] = count + 1
            slugs.add(slug if count == 0 else "%s-%d" % (slug, count))
    return slugs


def load():
    reqs = []
    for path in sorted((ROOT / "requirements").glob("REQ-*.md")):
        data = frontmatter(path)
        if not data.get("id") or data.get("status") not in STATUSES:
            raise TraceError("%s: needs an 'id' and a 'status' from: %s"
                             % (rel(path), ", ".join(STATUSES)))
        data["traces"] = data.get("traces") or {}
        reqs.append(data)
    steps = []
    for folder in FOLDERS:
        for path in sorted((ROOT / "workplan" / folder).glob("STEP-*.md")):
            data = frontmatter(path)
            if not data.get("id"):
                raise TraceError("%s: needs an 'id'" % rel(path))
            data["folder"] = folder
            data["evidence"] = data.get("evidence") or {}
            steps.append(data)
    reqs.sort(key=lambda r: r["id"])
    steps.sort(key=lambda s: s["id"])
    tags = scan_tags([CODE_ROOT] + ALSO_IMPLEMENTS, ("implements",))
    tags.update(scan_tags([TEST_ROOT] + ALSO_VERIFIES, ("verifies", "supports")))
    return reqs, steps, tags


def steps_of(req, steps):
    return [s for s in steps if req["id"] in as_list(s.get("implements"))]


def steps_done(req, steps):
    return all(s["folder"] == "done" for s in steps_of(req, steps) if not s.get("cancelled"))


def findings(reqs, steps, tags):
    """The coverage report: [(label, [entries])], in the order §4.3 step 6 lists them."""
    known = {r["id"] for r in reqs}
    heads = anchors()
    impl, ver = tags["implements"], tags["verifies"]
    orphans = sorted({"%s (%s in %s)" % (req, kind, name)
                      for kind, found in tags.items()
                      for req, places in found.items() if req not in known
                      for name, _ in places})
    broken = []
    for r in reqs:
        for link in as_list(r["traces"].get("architecture")):
            name, _, slug = str(link).partition("#")
            if name != ARCHITECTURE or slug not in heads:
                broken.append("%s (%s)" % (r["id"], link))
    no_evidence = [s["id"] for s in steps if s["folder"] == "done" and (
        not as_list(s["evidence"].get("commits")) or
        not (as_list(s["evidence"].get("tests")) or s["evidence"].get("notes")))]
    return [
        ("Unimplemented (approved, no code tag)",
         [r["id"] for r in reqs if r["status"] == "approved" and r["id"] not in impl]),
        ("Unverified (implemented, no tagged test)",
         [r["id"] for r in reqs if r["status"] == "implemented" and r["id"] not in ver]),
        ("Evidence missing (implemented or verified, tag gone)",
         [r["id"] for r in reqs
          if (r["status"] in ("implemented", "verified") and r["id"] not in impl)
          or (r["status"] == "verified" and r["id"] not in ver)]),
        ("Orphan tags", orphans),
        ("Done steps without evidence", no_evidence),
        ("Broken architecture anchors", broken),
        ("Needs re-verify", [r["id"] for r in reqs if r["status"] == "needs-reverify"]),
    ]


def proposals(reqs, steps, tags):
    """Status transitions (§3.2, "during §4.3") the scanned evidence supports."""
    out = []
    for r in reqs:
        rid, status = r["id"], r["status"]
        impl = rid in tags["implements"]
        ver = rid in tags["verifies"]
        ready = impl and steps_done(r, steps)
        if status == "approved" and ready:
            out.append((rid, status, "implemented", "code tag present, its steps are done"))
        elif status == "implemented" and not impl:
            out.append((rid, status, "needs-reverify", "EVIDENCE GONE: no code tag left"))
        elif status == "implemented" and ver:
            out.append((rid, status, "verified", "tagged test present; only if the suite passes"))
        elif status == "verified" and not (impl and ver):
            out.append((rid, status, "needs-reverify", "EVIDENCE GONE: code or test tag missing"))
        elif status == "needs-reverify" and ready:
            target = "verified" if ver else "implemented"
            out.append((rid, status, target, "evidence present again; only after rework and a passing suite"))
    return out


# --- output -----------------------------------------------------------------

def cell(values):
    return ", ".join(values).replace("|", "\\|") if values else "—"


def tagged_files(found, rid, suffix=""):
    return sorted({name + suffix for name, _ in found.get(rid, [])})


def body(reqs, steps, tags):
    lines = [
        BODY_START, "",
        "- `implements:` in " + ", ".join("`%s`" % r for r in [CODE_ROOT] + ALSO_IMPLEMENTS),
        "- `verifies:` / `supports:` in " + ", ".join("`%s`" % r for r in [TEST_ROOT] + ALSO_VERIFIES),
        "",
        "## Matrix", "",
        "| REQ | title | status | priority | architecture | steps | code | tests |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in reqs:
        rid = r["id"]
        links = ["#" + str(a).partition("#")[2] if str(a).startswith(ARCHITECTURE + "#") else str(a)
                 for a in as_list(r["traces"].get("architecture"))]
        step_cells = ["%s (%s)" % (s["id"], "cancelled" if s.get("cancelled") else s["folder"])
                      for s in steps_of(r, steps)]
        tests = tagged_files(tags["verifies"], rid) + tagged_files(tags["supports"], rid, " (supports)")
        lines.append("| " + " | ".join([
            rid, cell([str(r.get("title") or "")]), r["status"], str(r.get("priority") or "—"),
            cell(links), cell(step_cells), cell(tagged_files(tags["implements"], rid)), cell(tests),
        ]) + " |")
    lines += ["", "## Coverage report", ""]
    lines += ["- %s: %s" % (label, cell(entries)) for label, entries in findings(reqs, steps, tags)]
    return "\n".join(lines) + "\n"


def old_parts():
    """(statuses by REQ id, body) of the committed TRACE.md."""
    path = ROOT / TRACE
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.is_file() else ""
    rows = dict(re.findall(r"^\| (%s) \|(?:[^|\\]|\\.)*\| ([a-z-]+) \|" % REQ_ID, text, re.M))
    start = text.find(BODY_START)
    return rows, (text[start:] if start >= 0 else "")


def delta(reqs, old_rows):
    parts = ["%s %s->%s" % (r["id"], old_rows[r["id"]], r["status"])
             for r in reqs if r["id"] in old_rows and old_rows[r["id"]] != r["status"]]
    added = sum(1 for r in reqs if r["id"] not in old_rows)
    removed = len(set(old_rows) - {r["id"] for r in reqs})
    parts += ["+%d REQ" % added] if added else []
    parts += ["-%d REQ" % removed] if removed else []
    return "; ".join(parts) or "links changed"


def report(reqs, steps, tags):
    folders = ", ".join("%d %s" % (sum(s["folder"] == f for s in steps), f) for f in FOLDERS)
    print("%d requirement(s); steps: %s" % (len(reqs), folders))
    print("\nCoverage")
    for label, entries in findings(reqs, steps, tags):
        print("  %s: %s" % (label, ", ".join(entries) or "none"))
    print("\nTags")
    for kind in ("implements", "verifies", "supports"):
        for rid in sorted(tags[kind]):
            places = ", ".join("%s:%d" % place for place in tags[kind][rid])
            print("  %s %s: %s" % (kind, rid, places))
    print("\nTransitions the evidence supports (apply in §4.3 step 5)")
    found = proposals(reqs, steps, tags)
    for rid, old, new, why in found:
        print("  %s: %s -> %s (%s)" % (rid, old, new, why))
    if not found:
        print("  none")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--coverage", action="store_true", help="report only; write nothing")
    mode.add_argument("--check", action="store_true", help="exit 1 if TRACE.md is stale")
    args = parser.parse_args()

    reqs, steps, tags = load()
    if args.coverage:
        report(reqs, steps, tags)
        return 0

    new = body(reqs, steps, tags)
    old_rows, old = old_parts()
    if new == old:
        print("%s is up to date" % TRACE)
        return 0
    if args.check:
        sys.stderr.writelines(difflib.unified_diff(
            old.splitlines(True), new.splitlines(True), TRACE, "fresh scan"))
        sys.stderr.write("%s is stale: run ./dev trace (python3 scripts/trace.py)\n" % TRACE)
        return 1
    stamp = "%s: %s" % (datetime.date.today().isoformat(), delta(reqs, old_rows))
    text = "\n".join([HEADER, "", "# Traceability matrix", "",
                      "## Generation stamp", "", stamp, "", new])
    with open(ROOT / TRACE, "w", encoding="utf-8", newline="\n") as out:
        out.write(text)
    print("wrote %s (%s)" % (TRACE, stamp))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except TraceError as err:
        sys.stderr.write("trace: %s\n" % err)
        sys.exit(2)
